live_config_reload = true

[window]
opacity=0.9

[colors]
primary.foreground="#88ff33"

[selection]
save_to_clipboard=true

[cursor]
style.blinking="On"

[mouse]
hide_when_typing=true

[keyboard]
bindings = [
  { key = "n", mods = "Control|Shift", action = "SpawnNewInstance" }
]
